title: "Japheth's Portfolio"
#logo 
description: Web3 community manager and growth strategist helping DeFi, AI, and GameFi projects grow through on-chain insight, structured engagement, and long-term community alignment.
#show downloads: true
theme: jekll-theme-minimal
